version: '3.8'

services:
  auth_server:
    build:
      context: ./auth_server
    ports:
      - "8080:8080"
    env_file:
      - ./auth_server/.env
    depends_on:
      - db

  flutter_app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "8081:8081"
    # network_mode: "bridge"
    command: ["flutter", "run", "-d", "web-server", "--web-port", "3000", "--web-hostname", "0.0.0.0"]
    depends_on:
      - auth_server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Stocker@365
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  db_data:
