// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG3UkRMibHfsshI1u_Frdn5xUSSv41roE',
    appId: '1:495424228106:web:2e80100715dc5011fb48f3',
    messagingSenderId: '495424228106',
    projectId: 'flutter-application-417418',
    authDomain: 'flutter-application-417418.firebaseapp.com',
    storageBucket: 'flutter-application-417418.appspot.com',
    measurementId: 'G-7NXS2V3NX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1NBhHr49V3qdVIbrZF8ytkF3BnLZyyNI',
    appId: '1:495424228106:android:6525eca4e630d449fb48f3',
    messagingSenderId: '495424228106',
    projectId: 'flutter-application-417418',
    storageBucket: 'flutter-application-417418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByO3urq97knQD0R8RIfpLkYcdlSl6XxbY',
    appId: '1:495424228106:ios:fbb37608c276e716fb48f3',
    messagingSenderId: '495424228106',
    projectId: 'flutter-application-417418',
    storageBucket: 'flutter-application-417418.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByO3urq97knQD0R8RIfpLkYcdlSl6XxbY',
    appId: '1:495424228106:ios:a7ec5613b63fc229fb48f3',
    messagingSenderId: '495424228106',
    projectId: 'flutter-application-417418',
    storageBucket: 'flutter-application-417418.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
